- hosts: localhost
  connection: local
  gather_facts: 'True'

  vars:
    local_home: "{{ lookup('env','HOME') }}"

    repos_git_user:
      - { src: "https://github.com/lesmyrmidons/dotfiles.git", dest: "~/.setup/dotfile" }
      - { src: "https://github.com/lesmyrmidons/zsh-config.git", dest: "~/.setup/zsh_config" }
      - { src: "https://github.com/lesmyrmidons/vim-config.git", dest: "~/.setup/vim_config" }
      - { src: "https://aur.archlinux.org/ulauncher.git", dest: "~/.setup/ulauncher" }

    repos_git_root:
      - { src: "https://github.com/ahmetb/kubectx", dest: "/opt/kubectx"}

    aur_packages:
      - { name: dive }
      - { name: google-chrome }

    app_image:
      - { name: Lens, src: https://api.k8slens.dev/binaries/latest.x86_64.AppImage, desc: "Lens - The Kubernetes IDE", category: Network }
#      - { name: Joplin, src: https://objects.joplinusercontent.com/v3.5.12/Joplin-3.5.12.AppImage?source=JoplinWebsite&type=New, desc: "Joplin - Note taking and to-do application", category: "Office" }
      - { name: CPU-X, src: https://github.com/TheTumultuousUnicornOfDarkness/CPU-X/releases/download/v5.4.0/CPU-X-5.4.0-x86_64.AppImage, desc: "CPU-X - Gathers information on CPU, motherboard and more", category: "System Tools" }
      - { name: Ledger, src: https://download.live.ledger.com/latest/linux, desc: "Ledger wallet desktop", options: " --no-sandbox", category: "Bank" }

    pacman_packages:
      - { name: antiword }
      - { name: bash-completion }
      - { name: bitwarden }
      - { name: code }
      - { name: curl }
      - { name: docker }
      - { name: fuse }
      - { name: git }
      - { name: go-task }
      - { name: hddtemp }
      - { name: helm, state: absent }
      - { name: htop }
      - { name: httpie }
      - { name: hwinfo }
      - { name: i2c-tools }
      - { name: krita }
      - { name: krita-plugin-gmic }
      - { name: kubectl }
      - { name: nvm }
      - { name: nvme-cli }
      - { name: obs-studio }
      - { name: pwgen }
      - { name: screenfetch }
      - { name: solaar }
      - { name: steam }
      - { name: tailspin }
      - { name: terminator }
      - { name: tig }
      - { name: timeshift }
      - { name: tmux }
      - { name: tree }
      - { name: vim }
      - { name: yarn }
      - { name: yay }
      - { name: zsh }
      - { name: vlc }

    flatpak_remotes:
      - { name: flathub, url: https://dl.flathub.org/repo/flathub.flatpakrepo }

    flatpak_packages:
      - { name: com.discordapp.Discord }
      - { name: org.flameshot.Flameshot }
      - { name: org.jellyfin.JellyfinDesktop }
      - { name: io.github.jorchube.monitorets }
      - { name: com.hunterwittenborn.Celeste }
      - { name: com.visualstudio.code }
      - { name: org.telegram.desktop }
      - { name: re.sonny.OhMySVG }
      - { name: io.missioncenter.MissionCenter }
      - { name: io.gitlab.librewolf-community }
      - { name: com.prusa3d.PrusaSlicer }
      - { name: org.signal.Signal }
      - { name: org.ferdium.Ferdium }
      - { name: com.github.PintaProject.Pinta }
      - { name: net.cozic.joplin_desktop }

    pip_packages:
      - { name: thefuck }
      - { name: Pygments }
      - { name: topgrade }
      - { name: gitup }
      - { name: go-task-bin }

    brew_packages:
      - { name: helm }
      - { name: kubecm }

    fonts_url:
      - { url: https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Regular.ttf }
      - { url: https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Bold.ttf }
      - { url: https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Italic.ttf }
      - { url: https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Bold%20Italic.ttf }

    link_user:
      - { src: ~/.setup/dotfile/gitconfig, dest: ~/.gitconfig }
      - { src: ~/.setup/dotfile/gitignore_global, dest: ~/.gitignore_global }
      - { src: ~/.setup/dotfile/_ansible.cfg, dest: ~/.ansible.cfg }
      - { src: ~/.setup/dotfile/_config/terminator, dest: ~/.config/terminator }
      - { src: ~/.setup/zsh_config/zshrc, dest: ~/.zshrc }
      - { src: ~/.setup/zsh_config/zsh_aliases, dest: ~/.zsh_aliases }
      - { src: ~/.setup/zsh_config/zsh_plugins.txt, dest: ~/.zsh_plugins.txt }
      - { src: /opt/kubectx/completion/kubectx.zsh, dest: /home/lesmyrmidons/.cache/antidote/https-COLON--SLASH--SLASH-github.com-SLASH-ohmyzsh-SLASH-ohmyzsh/cache/completions/_kubectx.zsh }
      - { src: /opt/kubectx/completion/kubens.zsh, dest: /home/lesmyrmidons/.cache/antidote/https-COLON--SLASH--SLASH-github.com-SLASH-ohmyzsh-SLASH-ohmyzsh/cache/completions/_kubens.zsh }
      - { src: ~/.setup/dotfile/logos, dest: ~/Pictures/logos }

    directories:
      - { src: "{{ local_home }}/.fonts" }
      - { src: "{{ local_home }}/.cache/antidote/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh/completions" }
      - { src: "{{ local_home }}/.kube" }

  handlers:
    - name: run fc-cache
      shell: fc-cache -vf
    - name: sensors
      become: 'True'
      shell: sensors-detect --auto

  tasks:
    - name: Update repositories ArchLinux
      become: 'True'
      community.general.pacman:
        update_cache: 'True'
        upgrade: 'True'
      tags:
        - pacman
        - apps
        - dotfile

    - name: Install packages ArchLinux
      become: 'True'
      package:
        name: "{{ item.name }}"
        state: "{{ item.state|default('present') }}"
      with_items: "{{ pacman_packages }}"
      ignore_errors: 'True'
      notify:
        - sensors
      tags:
        - pacman
        - apps
        - dotfile

    - name: Install packages AUR ArchLinux
      become: 'True'
      community.general.pacman:
        name: "{{ item.name }}"
        state: "{{ item.state|default('present') }}"
        executable: yay
#        extra_args: --builddir /var/cache/yay
      with_items: "{{ aur_packages }}"
      ignore_errors: 'True'
      tags:
        - pacman
        - apps
        - dotfile

    - name: Check if UV is installed
      ansible.builtin.stat:
        path: "/home/lesmyrmidons/.local/bin/uv"
      register: uv_stat
      tags:
        - uv
        - python
        - dotfile

    - block:
      - name: Install UV
        ansible.builtin.shell: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      when: not uv_stat.stat.exists
      environment:
        PATH: "/home/lesmyrmidons/.local/bin:{{ ansible_env.PATH }}"
      tags:
        - uv
        - python
        - dotfile

    # Flatpak store install
    - name: Add flatpak remote
      community.general.flatpak_remote:
        name: "{{ item.name }}"
        state: "{{ item.state|default('present') }}"
        flatpakrepo_url: "{{ item.url }}"
        method: user
      with_items: "{{ flatpak_remotes }}"
      tags:
        - flatpak
        - apps

    - name: Install flatpak packages
      community.general.flatpak:
        name: "{{ item.name }}"
        state: "{{ item.state|default('present') }}"
        remote: "{{ item.remote|default('flathub') }}"
        method: user
      with_items: "{{ flatpak_packages }}"
      tags:
        - flatpak
        - apps

    # configure zsh
    - name: Change default shell for {{ lookup('env','USER') }}
      become: 'True'
      user:
        name: "{{ lookup('env','USER') }}"
        shell: /bin/zsh
        groups: "{{ lookup('env','USER') }}"
        append: 'True'
      tags:
        - zsh
        - dotfile

    # install repositories github
    - name: git clone all repositories user
      git:
        repo: "{{ item.src }}"
        dest: "{{ item.dest }}"
        force: 'True'
        update: 'True'
        recursive: 'False'
        track_submodules: 'False'
      with_items: "{{ repos_git_user }}"
      tags:
        - zsh
        - dotfile

    - name: Git clone all repositories root
      become: 'True'
      git:
        repo: "{{ item.src }}"
        dest: "{{ item.dest }}"
        force: 'True'
      with_items: "{{ repos_git_root }}"
      tags:
        - k8s
        - dotfile

    - name: Install all application of type AppImage
      include_tasks: app_image.yml
      loop: "{{ app_image }}"

    - name: Install apps Python
      ansible.builtin.shell: |
        uv tool install "{{ item.name }}"
      with_items: "{{ pip_packages }}"
      tags:
        - zsh
        - python
        - dotfile

    - name: Check if Ulauncher is installed
      ansible.builtin.stat:
        path: "/usr/bin/ulauncher"
      register: ulauncher_stat
      tags:
        - apps

    - block:
      - name: Install ulauncher
        ansible.builtin.shell: |
          cd ~/.setup/ulauncher && makepkg -is
        tags:
          - apps
      when: not ulauncher_stat.stat.exists
      tags:
        - apps

    - name: Create Symlink for git
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        force: 'True'
        state: link
      with_items: "{{ link_user }}"
      tags:
        - zsh
        - dotfile

    # Create folder for fonts
    - name: Create folder for fonts
      file:
        path: "{{ item.src }}"
        state: directory
        mode: '0755'
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
      with_items: "{{ directories }}"
      tags:
        - zsh
        - dotfile

    # Download fonts
    - name: Download fonts
      get_url:
        url: "{{ item.url }}"
        dest: "{{ local_home }}/.fonts/"
        mode: '0644'
      with_items: "{{ fonts_url }}"
      notify: run fc-cache
      tags:
        - zsh
        - dotfile

    - name: Check if Homebrew is installed
      ansible.builtin.stat:
        path: "/home/linuxbrew/.linuxbrew/bin/brew"
      register: brew_stat
      tags:
        - brew
        - dotfile

    - block:
      - name: Install Homebrew
        ansible.builtin.shell: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      when: not brew_stat.stat.exists
      environment:
        PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"
      tags:
        - brew
        - dotfile

    - name: Install brew packages
      community.general.homebrew:
        name: "{{ item.name }}"
        state: "{{ item.state|default('present') }}"
        update_homebrew: true
      with_items: "{{ brew_packages }}"
      tags:
        - brew
        - apps
